name: Create Jira Bug Card on Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  create-jira-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Jira Bug Card
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_ORGANIZATION_ID: ${{ secrets.JIRA_ORGANIZATION_ID }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: "TEST" # Replace with your Jira project key
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue type: ${{ github.event.issue.labels.*.name}}"
