name: Create Jira Bug Card on Issue Creation

on:
  issues:
    types:
      - opened

jobs:

  run_dbt_cloud_job:
    name: Run dbt Cloud Job
    runs-on: ubuntu-latest
    
    

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"   
          cache: 'pip' # caching pip dependencies
      - run: pip install -r python/requirements.txt
      - name: push_jira_bug_card
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_ORGANIZATION_ID: ${{ secrets.JIRA_ORGANIZATION_ID }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          JIRA_PROJECT_KEY: "TEST"
          GITHUB_ISSUE_TYPE: ${{ toJson(github.event.issue.labels.*.name) }}
          GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
        run: "python python/push_jira_bug_card.py"
