name: Create Jira Bug Card on Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  create-jira-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Jira Bug Card
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_ORGANIZATION_ID: ${{ secrets.JIRA_ORGANIZATION_ID }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: "TEST" # Replace with your Jira project key
        run: |
          LABELS="${{ toJson(github.event.issue.labels.*.name) }}"
          if [[ $LABELS == *'"bug"'* ]]; then
            echo "Found bug label"
            echo "has_bug_label=true" >> $GITHUB_ENV
          else
            echo "Bug label not found"
            echo "has_bug_label=false" >> $GITHUB_ENV

      - name: Further steps
        if: env.has_bug_label == 'true'
        run: |
          echo "Executing steps for issues with bug label"
